"""create employees table

Revision ID: 0b5b2edff285
Revises:
Create Date: 2025-11-19 16:07:41.288886

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0b5b2edff285"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
