"""add sales_rep foreign key to customers

Revision ID: 4177a5ef2d93
Revises: a17698ca7aa3
Create Date: 2025-11-20 02:31:28.339188+00:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4177a5ef2d93"
down_revision: Union[str, Sequence[str], None] = "a17698ca7aa3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_customers_sales_rep_employee_number",
        "customers",
        "employees",
        ["sales_rep_employee_number"],
        ["employee_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_customers_sales_rep_employee_number",
        "customers",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
