"""create employees table

Revision ID: 2f34c730a42d
Revises: 839d854ed7e9
Create Date: 2025-11-19 21:31:00.522023

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f34c730a42d"
down_revision: Union[str, Sequence[str], None] = "839d854ed7e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("employee_number", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("job_title", sa.String(length=50), nullable=False),
        sa.Column("office_code", sa.String(length=10), nullable=True),
        sa.Column("reports_to", sa.Integer, nullable=True),
        sa.PrimaryKeyConstraint("employee_number"),
        sa.ForeignKeyConstraint(["reports_to"], ["employees.employee_number"]),
        sa.ForeignKeyConstraint(["office_code"], ["offices.office_code"]),
        sa.UniqueConstraint("email", name="unique_email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employees")
    # ### end Alembic commands ###
