"""make employee office_code and reports_to nullable

Revision ID: a17698ca7aa3
Revises: 8778cce349c7
Create Date: 2025-11-20 02:16:12.470733+00:00

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a17698ca7aa3"
down_revision: Union[str, Sequence[str], None] = "8778cce349c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "office_code",
        existing_type=mysql.VARCHAR(length=10),
        nullable=True,
    )
    op.alter_column(
        "employees",
        "reports_to",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "reports_to",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.alter_column(
        "employees",
        "office_code",
        existing_type=mysql.VARCHAR(length=10),
        nullable=False,
    )
    # ### end Alembic commands ###
