"""add customers table

Revision ID: 8778cce349c7
Revises: 2f34c730a42d
Create Date: 2025-11-20 02:12:44.101170+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8778cce349c7"
down_revision: Union[str, Sequence[str], None] = "2f34c730a42d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_number", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=50), nullable=False),
        sa.Column("contact_last_name", sa.String(length=50), nullable=False),
        sa.Column("contact_first_name", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("address_line_1", sa.String(length=50), nullable=False),
        sa.Column("address_line_2", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("postal_code", sa.String(length=15), nullable=True),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.Column("sales_rep_employee_number", sa.Integer(), nullable=True),
        sa.Column("credit_limit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("customer_number"),
    )
    op.alter_column(
        "employees",
        "office_code",
        existing_type=mysql.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "employees",
        "reports_to",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.alter_column(
        "offices",
        "address_line_1",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "offices",
        "address_line_2",
        existing_type=mysql.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "offices", "country", existing_type=mysql.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "offices", "country", existing_type=mysql.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "offices",
        "address_line_2",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "offices",
        "address_line_1",
        existing_type=sa.String(length=255),
        type_=mysql.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "employees",
        "reports_to",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    op.alter_column(
        "employees",
        "office_code",
        existing_type=mysql.VARCHAR(length=10),
        nullable=True,
    )
    op.drop_table("customers")
    # ### end Alembic commands ###
