"""create offices table

Revision ID: 839d854ed7e9
Revises:
Create Date: 2025-11-19 16:09:47.971496

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "839d854ed7e9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offices",
        sa.Column("office_code", sa.String(10), nullable=False),
        sa.PrimaryKeyConstraint("office_code"),
        sa.Column("city", sa.String(100), nullable=False),
        sa.Column("phone", sa.String(50), nullable=True),
        sa.Column("address_line_1", sa.String(100), nullable=True),
        sa.Column("address_line_2", sa.String(100), nullable=True),
        sa.Column("state", sa.String(50), nullable=True),
        sa.Column("country", sa.String(50), nullable=False),
        sa.Column("postal_code", sa.String(10), nullable=True),
        sa.Column("territory", sa.String(10), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offices")
    # ### end Alembic commands ###
