name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-python@v3
        with:
          python-version: "3.12"
      - run: pip install uv
      - run: uv sync
      - run: uv run pytest
